### ISSUE TITLE
Showing attribute error

### ISSUE THREAD

**Issue by rsoorajs** [FayasNoushad/GoFile-Bot#15]
Showing attribute error

```
2021-12-07T09:07:13.995166+00:00 app[worker.1]: 'NoneType' object has no attribute 'startswith'
2021-12-07T09:07:13.995174+00:00 app[worker.1]: Traceback (most recent call last):
2021-12-07T09:07:13.995174+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
2021-12-07T09:07:13.995175+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2021-12-07T09:07:13.995175+00:00 app[worker.1]:   File "/app/main.py", line 33, in filter
2021-12-07T09:07:13.995175+00:00 app[worker.1]:     if not update.text.startswith("http://") or not update.text.startswith("https://"):
2021-12-07T09:07:13.995176+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'startswith'
2021-12-07T09:08:07.259086+00:00 app[worker.1]: 'NoneType' object has no attribute 'startswith'
2021-12-07T09:08:07.259096+00:00 app[worker.1]: Traceback (most recent call last):
2021-12-07T09:08:07.259098+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
2021-12-07T09:08:07.259098+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2021-12-07T09:08:07.259098+00:00 app[worker.1]:   File "/app/main.py", line 33, in filter
2021-12-07T09:08:07.259105+00:00 app[worker.1]:     if not update.text.startswith("http://") or not update.text.startswith("https://"):
2021-12-07T09:08:07.259106+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'startswith'
2021-12-07T09:08:48.501101+00:00 app[worker.1]: 'NoneType' object has no attribute 'startswith'
2021-12-07T09:08:48.501109+00:00 app[worker.1]: Traceback (most recent call last):
```

**Comment by FayasNoushad** [comment]
Fixed

**Comment by rsoorajs** [comment]
> Fixed

not fixed yet. still showing the same error
