### ISSUE TITLE
File is downloading on server but it is not able to upload on gofile server.

### ISSUE THREAD

**Issue by mjwebhacks** [FayasNoushad/GoFile-Bot#18]
Check this log from Heroku given below:

'directLink'
2022-05-02T04:51:40.174770+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-02T04:51:40.174779+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
2022-05-02T04:51:40.174779+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-05-02T04:51:40.174779+00:00 app[worker.1]:   File "/app/main.py", line 62, in filter
2022-05-02T04:51:40.174780+00:00 app[worker.1]:     text += f"**Direct Download Link:** `{response['directLink']}`" + "\n"
2022-05-02T04:51:40.174780+00:00 app[worker.1]: KeyError: 'directLink'

**Comment by FayasNoushad** [comment]
Can you try again

**Comment by mjwebhacks** [comment]
yes, it is working now. One more issue I have fixed in the download link as per the GoFile API response check it out.

text += f"**Direct Download Link:** `{response['directLink'] + '/' + response['fileName']}`" + "\n"

**Comment by FayasNoushad** [comment]
Ohh! I will add that.

**Comment by FayasNoushad** [comment]
Fixed successfully

https://github.com/FayasNoushad/GoFile-Bot/commit/dd664923034635fd51bcdd3f7cb98c627d5974dd
