### ISSUE TITLE
Bot not responding

### ISSUE THREAD

**Issue by FayasNoushad** [FayasNoushad/GoFile-Bot#28]
Bot not responding check logs

2022-05-05T07:52:53.491005+00:00 heroku[worker.1]: State changed from starting to up
�2022-05-05T07:53:18.424092+00:00 app[worker.1]: cannot unpack non-iterable NoneType object
2022-05-05T07:53:18.424131+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-05T07:53:18.424134+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
2022-05-05T07:53:18.424134+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-05-05T07:53:18.424134+00:00 app[worker.1]:   File "/app/main.py", line 46, in filter
2022-05-05T07:53:18.424137+00:00 app[worker.1]:     url, token, folderId = None
2022-05-05T07:53:18.424140+00:00 app[worker.1]: TypeError: cannot unpack non-iterable NoneType object
�2022-05-05T07:53:37.512081+00:00 app[worker.1]: cannot unpack non-iterable NoneType object
2022-05-05T07:53:37.512104+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-05T07:53:37.512106+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
2022-05-05T07:53:37.512106+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-05-05T07:53:37.512107+00:00 app[worker.1]:   File "/app/main.py", line 46, in filter
2022-05-05T07:53:37.512107+00:00 app[worker.1]:     url, token, folderId = None
2022-05-05T07:53:37.512108+00:00 app[worker.1]: TypeError: cannot unpack non-iterable NoneType object

_Originally posted by @mjwebhacks in https://github.com/FayasNoushad/GoFile-Bot/issues/27#issuecomment-1118377009_

**Comment by FayasNoushad** [comment]
Fixed successfully
